[build]
    command = "npm run build"
    publish = ".next"

[[plugins]]
package = “@netlify/plugin-nextjs”

[context.production.environment]
NEXT_SERVERLESS = “true”

[functions]
  included_files = [".next/*.json"]
  node_bundler = "esbuild"