module.exports = {
  distDir: 'out',
  webpack: (configuration) => {
    configuration.module.rules.push({
      test: /\.md$/,
      use: 'frontmatter-markdown-loader',
    })
    return configuration
  },
  generateBuildId: async () => {
    // You can, for example, get the latest git commit hash here
    return 'my-build-id'
  },
  async redirects() {
    return [
      {
        source: '/admin', 
        destination: '/editor', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/abbs-edge', 
        destination: '/abbs-edge/recognition-accreditations', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/profile/', 
        destination: '/profile/history-overview', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty', 
        destination: '/faculty/profiles', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/research', 
        destination: '/research/research-centre', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/corporate', 
        destination: '/corporate/recruit-students', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/campus-life', 
        destination: '/campus-life/health-wellness', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-events', 
        destination: '/news-events/news', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/campus-life/clubs-associations', 
        destination: '/campus-life/health-wellness', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/campus-life/student-support', 
        destination: '/campus-life/health-wellness', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/business', 
        destination: '/programs/business/business-programs', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/life-sciences', 
        destination: '/programs/life-sciences/life-sciences-programs', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/commerce', 
        destination: '/programs/commerce/commerce-programs', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/liberal-arts', 
        destination: '/programs/liberal-arts/liberal-arts-programs', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/information-technology', 
        destination: '/programs/information-technology/information-technology-programs', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/mcom-colleges-in-bangalore/',
        destination: '/programs/commerce/m-com',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/bba-colleges-in-bangalore/',
        destination: '/programs/business/bba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/bba-aviation-colleges-in-bangalore/',
        destination: '/programs/business/bba-aviation-management',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/b-sc-biotechnology-colleges-in-bangalore/',
        destination: '/programs/life-sciences/b-sc',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/bcom-colleges-in-bangalore/',
        destination: '/programs/commerce/b-com',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/ba-journalism-colleges-in-bangalore/',
        destination: '/programs/liberal-arts/ba-journalism',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/bca-colleges-in-bangalore/',
        destination: '/programs/information-technology/bca',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/mba-colleges-in-bangalore/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/abbs-blog/',
        destination: '/blog',
        permanent: false,
        basePath: false,
      },
      {
        source: '/parents/gd-pi/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/abbs-profile/history-and-overview/',
        destination: '/profile/history-overview',
        permanent: false,
        basePath: false,
      },
      {
        source: '/abbs-profile/mission-values/',
        destination: '/profile/vision-mission',
        permanent: false,
        basePath: false,
      },
      {
        source: '/abbs-profile/impact/',
        destination: '/profile/impact',
        permanent: false,
        basePath: false,
      },
      {
        source: '/abbs-profile/leadership-management-team/',
        destination: '/profile/leadership-team',
        permanent: false,
        basePath: false,
      },
      {
        source: '/abbs-profile/advisory-council/',
        destination: '/profile/advisory-council',
        permanent: false,
        basePath: false,
      },
      {
        source: '/abbs-profile/visiting-us/',
        destination: '/profile/visiting-us',
        permanent: false,
        basePath: false,
      },
      {
        source: '/abbs-profile/virtual-campus-tour/',
        destination: '/profile/virtual-campus-tour',
        permanent: false,
        basePath: false,
      },
      {
        source: '/whyabbs/recognition-accreditations/',
        destination: '/abbs-edge/recognition-accreditations',
        permanent: false,
        basePath: false,
      },
      {
        source: '/whyabbs/facts-figures/',
        destination: '/abbs-edge/fact-figures',
        permanent: false,
        basePath: false,
      },
      {
        source: '/whyabbs/learning-excellence/',
        destination: '/abbs-edge/learning-excellence',
        permanent: false,
        basePath: false,
      },
      {
        source: '/whyabbs/international-associations/',
        destination: '/abbs-edge/international-associations',
        permanent: false,
        basePath: false,
      },
      {
        source: '/whyabbs/knowledge-partners/',
        destination: '/abbs-edge/knowledge-partners',
        permanent: false,
        basePath: false,
      },
      {
        source: '/whyabbs/equality-diversity-and-inclusion/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/',
        destination: '/programs',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/pg-diploma-in-management/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/faculties/',
        destination: '/faculty/profiles',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/research-development/',
        destination: '/faculty/profiles',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/libraries-labs/',
        destination: '/faculty/infrastructure',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/startup-center/',
        destination: '/faculty/entrepreneurship',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/news-and-events/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/publications/',
        destination: '/research/research-publications',
        permanent: false,
        basePath: false,
      },
      {
        source: '/corporate/recruit-our-students/',
        destination: '/corporate/recruit-students',
        permanent: false,
        basePath: false,
      },
      {
        source: '/corporate/consultancy/',
        destination: '/corporate/consultancy-mdp',
        permanent: false,
        basePath: false,
      },
      {
        source: '/corporate/management-development-programs-mdp/',
        destination: '/corporate/consultancy-mdp',
        permanent: false,
        basePath: false,
      },
      {
        source: '/corporate/mentoring/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/corporate/guest-lectures/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/corporate/r-support/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/campus-life/health-wellness/',
        destination: '/campus-life/health-wellness',
        permanent: false,
        basePath: false,
      },
      {
        source: '/campus-life/recreational-sports/',
        destination: '/campus-life/recreational-sports',
        permanent: false,
        basePath: false,
      },
      {
        source: '/campus-life/womens-wing/',
        destination: '/campus-life/womens-wing',
        permanent: false,
        basePath: false,
      },
      {
        source: '/campus-life/clubs/',
        destination: '/campus-life/clubs-associations/toastmaster',
        permanent: false,
        basePath: false,
      },
      {
        source: '/campus-life/housing-dining/',
        destination: '/campus-life/hostels',
        permanent: false,
        basePath: false,
      },
      {
        source: '/campus-life/safety-security/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/admission-aid/apply-now/',
        destination: 'https://application.abbs.edu.in/bschool',
        permanent: false,
        basePath: false,
      },
      {
        source: '/admission-aid/postgraduate-programmes/',
        destination: '/admissions/program-requirements',
        permanent: false,
        basePath: false,
      },
      {
        source: '/admission-aid/undergraduate-programmes/',
        destination: '/admissions/program-requirements',
        permanent: false,
        basePath: false,
      },
      {
        source: '/admission-aid/international-students-2/',
        destination: '/admissions/international-students',
        permanent: false,
        basePath: false,
      },
      {
        source: '/admission-aid/scholarships/',
        destination: '/admissions/fees-scholarships',
        permanent: false,
        basePath: false,
      },
      {
        source: '/admission-aid/application-deadlines/',
        destination: '/admissions/admission-deadlines',
        permanent: false,
        basePath: false,
      },
      {
        source: '/admission-aid/admission-faqs/',
        destination: '/admissions/admission-faqs',
        permanent: false,
        basePath: false,
      },
      {
        source: '/admission-aid/contact-admission-office/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/latest-news/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-events/',
        destination: '/news-events/events',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/iacbe-accredited-programmes/',
        destination: '/mandatory-disclosures/category/iacbe',
        permanent: false,
        basePath: false,
      },
      {
        source: '/admission-aid/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/financial-aid/',
        destination: '/admissions/financial-aid',
        permanent: false,
        basePath: false,
      },
      {
        source: '/careers/',
        destination: '/careers-at-abbs',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mandatory-disclosures/',
        destination: '/mandatory-disclosures',
        permanent: false,
        basePath: false,
      },
      {
        source: '/gallery/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/grievance-redressal/',
        destination: '/grievance-redressal',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/bba-colleges-in-bangalore/',
        destination: '/programs/business/bba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/12/Semester-Wise-Syllabus-MBA-1.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2020/07/PG-Diploma-in-Management.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2020/07/ABBS-MCom-Brochure.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/12/Semester-Wise-Syllabus-BBA-1.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2020/06/BSc-Biotechnology.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/12/Semester-Wise-Syllabus-BCom-1.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/12/Semester-Wise-Syllabus-BA-1.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/12/Semester-Wise-Syllabus-BCA-1.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/faculties/page/2/',
        destination: '/faculty/profiles',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/faculties/page/8/',
        destination: '/faculty/profiles',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/faculties/page/9/',
        destination: '/faculty/profiles',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/08/ABBS-PLACEMENT-POLICY.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/campus-life/student-council/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2019/07/ABBS-Hostel-RulesRegulations-2019.pdf',
        destination: '/campus-life/hostels',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/the-millionaire-millennial/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/re-emergence-of-agile-and-scrum-in-project-management-2/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/performing-arts/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/the-alchemist-mindset/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/abbs-ranked-31st-in-india-and-5th-in-karnataka-under-best-private-b-schools-rankings-2020-education-world/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/title-10-mba-students-placed-at-byjus-at-rs-10-lpa/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/abbs-ranked-39th-best-b-school-business-india-2019/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/rotaract-club-of-abbs/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/tedxabbswomen/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/latest-news/page/2/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/latest-news/page/3/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/latest-news/page/4/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/abbs-is-a-cii-member/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/10/The-Times-of-ABBS-Vol-1-Issue-1-Sept-2010.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/09/ABBS_Times_Vol_1.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/10/The-Times-of-ABBS-Vol-2-Issue-1-Mar-2011.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/11/The-Times-of-ABBS-Vol-2-Issue-2-Sept-2011.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/10/The-Times-of-ABBS-Vol-3-Issue-1-Nov-2012.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/10/The-Times-of-ABBS-Vol-3-Issue-2-Mar-2013.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/10/The-Times-of-ABBS-Vol-4-Issue-1-Sept-2013.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/10/The-Times-of-ABBS-Vol-4-Issue-2-Mar-2014.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/10/The-Times-of-ABBS-Vol-5-Issue-2-Mar-2015.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/10/The-Times-of-ABBS-Vol-6-Issue-3-Sept-2015.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/10/The-Times-of-ABBS-Vol-7-Issue-1-Mar-2016.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/10/The-Times-of-ABBS-Vol-7-Issue-2-Mar-2017.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/11/Times-of-ABBS_-VOL-10_October-2018.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/11/Times-of-ABBS_-VOL-11_November-2018.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/12/ABBS_Times_Final_Dec_18.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2019/02/ABBS-TIMES-Jan-2019.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/about-us/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/vision-mission/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/chairmans-message/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/director-message/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/governing-council/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/advisory-board/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/paqi/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/infrastructure/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/programs/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/admissions/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/faculty/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/core-faculty/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/adjunct-faculty/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/faculty-publications/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/students/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/placements/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/events/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/publications/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/contact-us/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/mandatory-disclosures/',
        destination: '/programs/business/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2019/07/IACBE.pdf',
        destination: '/static/img/IACEB_2021.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2020/01/IACBE-Student-Achievement.pdf',
        destination: '/static/img/IACEB_2021.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2019/11/AQAR-2017-18-Collegecode-12283.pdf',
        destination: '/static/img/AQAR-2017-18-Collegecode-12283.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/08/AQAR-2016-17-Collegecode-12283.pdf',
        destination: '/static/img/AQAR-2016-17-Collegecode-12283.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2019/12/ABBS-IQAC.pdf',
        destination: '/static/img/Internal Quality Assurance Cell.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/03/Accreditations.pdf',
        destination: '/static/img/Accreditations-NAAC-cycle 2.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/08/IACBE-Certificate-of-Accreditation.pdf',
        destination: '/static/img/IACEB_2021.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2018/08/AICTE-OA-Report_2018-19.pdf',
        destination: '/static/img/AICTE-OA-Report_2018-19.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2019/04/FormNo_10B.pdf',
        destination: '/static/img/FormNo_10B.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2019/12/Hand-Book-inner-17-18.pdf',
        destination: '/static/img/Hand-Book-inner-17-18.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2019/12/Hand-Book-2018-21.pdf',
        destination: '/static/img/Hand-Book-2018-21.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/gallery/campus-tours/',
        destination: '/profile/virtual-campus-tour',
        permanent: false,
        basePath: false,
      },
      {
        source: '/gallery/infrastructur/',
        destination: '/profile/virtual-campus-tour',
        permanent: false,
        basePath: false,
      },
      {
        source: '/gallery/abbs-fests/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/gallery/sports-meet/',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/faculties/page/3/',
        destination: '/faculty/profiles',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/faculties/page/7/',
        destination: '/faculty/profiles',
        permanent: false,
        basePath: false,
      },
      {
        source: '/wp-content/uploads/2020/07/MDP-Re-emergence-of-Agile-and-Scrum-in-Project-Management.pdf',
        destination: '/corporate/consultancy-mdp',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/61st-kannada-rajyitsava/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/pre-engagement-of-tedx-abbs/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/tedx-abbs-pre-event/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/mou-signed-with-millionminds/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/nba-accredited/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/accelerate-the-startup-talk/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/bidding-game/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/national-conference-on-industry-4-0-its-implication-on-businessess/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/endophytes-and-its-secondary-metabolites/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/elysian/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/4300/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/bizomania-2019/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/mba-placement-news/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/icici-securities-placements/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/toyota-kirloskar-industrial-visit/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/entrepreneurship-awareness-camp-for-b-c-a-students/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/national-conference-on-msme/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/student-conference/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/industrial-visit/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/women-entrepreneurs/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-event/8th-international-conference-on/',
        destination: '/news-events/news',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/01/Course-matrix.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/01/Academic-Process.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/04/MBA_Best-Pratice.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/01/ABBS-SEP-2018.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/01/ABBS-OCT-2018.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/01/ABBS-NOV-2018.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/01/ABBS-DEC-2018.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/03/ABBS-TIMES-Jan-2019.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/04/Volume-10-Issue-1-Amber.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/04/ABBS-International-Conference-Ethics-Peace-Economics-and-Science-2019.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/01/ARC-ABBS.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/04/Antiragging-Committee.pdf',
        destination: '/campus-life/student-support/anti-ragging-committee-members',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/01/GRC-ABBS.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/01/SHRC-ABBS.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/04/SHC2018.pdf',
        destination: '/',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/04/FormNo_10B.pdf',
        destination: '/static/img/FormNo_10B.pdf',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/04/employee-handbook.pdf',
        destination: '/programs/busness/mba',
        permanent: false,
        basePath: false,
      },
      {
        source: '/mba/wp-content/uploads/2019/04/Mandatory-Disclosure-2019.pdf',
        destination: '/mandatory-disclosures',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/faculties/page/4/',
        destination: '/faculty/profiles',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/faculties/page/6/',
        destination: '/faculty/profiles',
        permanent: false,
        basePath: false,
      },
      {
        source: '/faculty-research/faculties/page/5/',
        destination: '/faculty/profiles',
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/business/mba', 
        destination: '/programs/business/best-mba-colleges-in-bangalore', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/business/bba', 
        destination: '/programs/business/bba-colleges-in-bangalore', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/business/bba-aviation-management', 
        destination: '/programs/business/bba-aviation-colleges-in-bangalore', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/commerce/m-com', 
        destination: '/programs/commerce/m-com-colleges-in-bangalore', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/commerce/b-com', 
        destination: '/programs/commerce/b-com-colleges-in-bangalore', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/life-sciences/b-sc', 
        destination: '/programs/life-sciences/b-sc-biotechnology-colleges-in-bangalore', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/information-technology/bca', 
        destination: '/programs/information-technology/bca-colleges-in-bangalore', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/liberal-arts/ba-journalism', 
        destination: '/programs/liberal-arts/ba-journalism-colleges-in-bangalore', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/liberal-arts/ba-economics', 
        destination: '/programs/liberal-arts/ba-economics-colleges-in-bangalore', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/liberal-arts/ba-psychology', 
        destination: '/programs/liberal-arts/ba-sociology-colleges-in-bangalore', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/conferences/ABBSICC2022', 
        destination: '/conferences/international-case-conference-2022', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/mandatory-disclosures/category/terms-and-conditions', 
        destination: '/', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/blog/category/terms-and-conditions', 
        destination: '/', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/mandatory-disclosures/category/privacy-policy', 
        destination: '/', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/news-events/static/img/00-abbs-logo-black.svg', 
        destination: '/', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/programs/static/img/00-abbs-logo-black.svg', 
        destination: '/', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/mandatory-disclosures/static/img/00-abbs-logo-black.svg', 
        destination: '/', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/blog/static/img/00-abbs-logo-black.svg', 
        destination: '/', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/undefined', 
        destination: '/', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/abbs-profile/advisory-council', 
        destination: '/profile/advisory-council', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/admissions/fees-scholarships', 
        destination: '/admissions/fees-scholarships-ug', 
        permanent: false,
        basePath: false,
      },
      {
        source: '/lp/mba-analytics',
        destination: '/lp/mba-analytics/index.html',
        permanent: false,
        basePath: false,
      },
      {
        source: '/lp/mba',
        destination: '/lp/mba/index.html',
        permanent: false,
        basePath: false,
      },
      {
        source: '/lp/PGDM',
        destination: '/lp/PGDM/index.html',
        permanent: false,
        basePath: false,
      },
      {
        source: '/lp/ug',
        destination: '/lp/ug/index.html',
        permanent: false,
        basePath: false,
      },
      {
        source: '/lp/mba-analytics/thank-you',
        destination: '/lp/mba-analytics/thank-you.html',
        permanent: false,
        basePath: false,
      },
      {
        source: '/lp/mba/thankyou',
        destination: '/lp/mba/thankyou.html',
        permanent: false,
        basePath: false,
      },
      {
        source: '/lp/PGDM/thankyou',
        destination: '/lp/PGDM/thankyou.html',
        permanent: false,
        basePath: false,
      },
      {
        source: '/lp/ug/thankyou',
        destination: '/lp/ug/thankyou.html',
        permanent: false,
        basePath: false,
      },
      {
        source: '/lp/allprograms',
        destination: '/lp/allprograms/index.html',
        permanent: false,
        basePath: false,
      },
      {
        source: '/lp/allprograms/thankyou',
        destination: '/lp/allprograms/thankyou.html',
        permanent: false,
        basePath: false,
      }
    ]
  },
  async rewrites() {
    return [
      {
        source: '/lp/mba-analytics',
        destination: '/lp/mba-analytics/index.html'
      },
      {
        source: '/lp/mba',
        destination: '/lp/mba/index.html'
      },
      {
        source: '/lp/bba',
        destination: '/lp/bba/index.html'
      },
      {
        source: '/lp/bca',
        destination: '/lp/bca/index.html'
      },
      {
        source: '/lp/PGDM',
        destination: '/lp/PGDM/index.html'
      },
      {
        source: '/lp/ug',
        destination: '/lp/ug/index.html'
      },
      {
        source: '/lp/allprograms',
        destination: '/lp/allprograms/index.html'
      },
      {
        source: '/lp/mba-analytics/thank-you',
        destination: '/lp/mba-analytics/thank-you.html'
      },
      {
        source: '/lp/mba/thankyou',
        destination: '/lp/mba/thankyou.html'
      },
      {
        source: '/lp/bba/thankyou',
        destination: '/lp/bba/thankyou.html'
      },
      {
        source: '/lp/bca/thankyou',
        destination: '/lp/bca/thankyou.html'
      },
      {
        source: '/lp/PGDM/thankyou',
        destination: '/lp/PGDM/thankyou.html'
      },
      {
        source: '/lp/ug/thankyou',
        destination: '/lp/ug/thankyou.html'
      },
      {
        source: '/lp/allprograms/thankyou',
        destination: '/lp/allprograms/thankyou.html'
      }
    ]
  }
}